app/categories/__init__.py
from flask import Blueprint

categories_blueprint = Blueprint('categories', __name__, url_prefix='/categories')

from app.categories  import views

app/categories/views.py
from app.categories import categories_blueprint
from flask import request, render_template, redirect, url_for
from app.models import Category, db
import os
from werkzeug.utils import secure_filename



@categories_blueprint.route('/index', endpoint='list')

def index():
    categories  = Category.get_all_objects()
    return render_template('layouts/base.html', categories=categories)
# 



@categories_blueprint.route('/create', endpoint='create',methods = ['GET', 'POST'])

def create():

    categories = Category.get_all_objects()

    if request.method == 'POST':
        # Get form data
        name = request.form['name']

        
        # Create a new Blog entry with the form data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()

        return redirect(url_for('posts.index'))

    return render_template('categories/create.html', categories=categories)

@categories_blueprint.route('<int:id>', endpoint='show')
def show(id):
    category = Category.get_specific_category(id)
    return  render_template('categories/show.html', category=category)

@categories_blueprint.route('<int:id>/delete', endpoint='delete')
def delete(id):
    category=Category.query.get_or_404(id)
    if category:
        db.session.delete(category)
        db.session.commit()
        return redirect(url_for('posts.index'))
    else:
        return '<h1> Object not found </h1>', 404
    

@categories_blueprint.route('<int:id>/edit', methods=['GET', 'POST'],endpoint='edit')
def edit(id):
    category = Category.query.get_or_404(id)
    if category:
        if request.method == 'POST':
            # Check if the name field is present in the request form
            if 'name' not in request.form:
                return render_template('categpries/edit.html', error='The name field is required.', category=category)

            # Check if the field name is correct
            if request.form['name'].strip() == '':
                return render_template('blogs/edit.html', error='The name field cannot be empty.', category=category)

            # Get the name and body values
            name = request.form['name']
            
            
            # Update the blog object
            category.name = name
            
            db.session.commit()

            return redirect(url_for('posts.index'))

        return render_template('categories/edit.html', category=category)

    return '<h1> Object not found </h1>', 404

app/templates/categories/create.html
{% extends 'layouts/base.html'%} 

{%block title%} New Category {%endblock%} 

{%block body%}
<h1 class="p-5 px-0">Add a new Category</h1>
<div class="container">
<form method="post" enctype="multipart/form-data" >
    <div class="mb-3">
      <label for="" class="form-label">Name</label>
      <input type="text"  name='name' class="form-control" id="" aria-describedby="emailHelp">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{%endblock%} 

app/templates/categories/edit.html
{% extends 'layouts/base.html'%} 

{%block title%} New Category {%endblock%} 

{%block body%}
<h1 class="p-5 px-0">Add a new Category</h1>
<div class="container">
<form method="post" enctype="multipart/form-data" >
    <div class="mb-3">
      <label for="" class="form-label">Name</label>
      <input type="text"  name='name' class="form-control" id="" aria-describedby="emailHelp">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{%endblock%} 

app/templates/categories/index.html
hiiii

app/templates/categories/show.html
{% extends 'layouts/base.html' %}
{% block title %} {{category.name}} {% endblock %}
{% block body %}
  <div class="container py-5">
    <h1 class="mb-4">Posts in {{category.name}} category</h1>
    <div class="row">
      {% for post in category.posts %}
      <div class="col-sm-6 mb-3 mb-sm-0 d-flex justify-content-center ">
        <div class="card mb-3 border-0 rounded rounded-0 " style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{post.get_image_url}}" class="img-fluid" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body py-0">
                <p class="card-title fw-semibold ">{{post.name}}</p>
                <p class="card-text">{{post.body}}</p>
                <p class="card-text"><small class="text-body-secondary">Last updated {{post.updated_at}}</small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="links">
      <a href="{{url_for('categories.delete', id=category.id)}}" class="btn btn-danger">Delete</a>
      <a href="{{url_for('categories.edit', id=category.id)}}" class="btn btn-danger">Edit</a>
    </div>
  </div>
{% endblock %}